### PR TITLE
romanToNumeral

### PR DESCRIPTION
**Pull request by dexkode4**

### CODE REVIEW

**Comment by bondz** [comment]
Trying to solve the other ones.

**Comment by dexkode4** [comment]
> Trying to solve the other ones.

**Comment by dexkode4** [comment]
I really don't understand gitflow ...plus there wasn't electricity, can I still make a PR ?

**Comment by bondz** [comment]
Yes @dexkode4 push your chnages to your repo's master branch and they would show up here.

**Pull request closed without merging**
